### ISSUE TITLE
Font readability on white background

### ISSUE THREAD

**Issue by MrJJJ** [joelshepherd/tabliss#121]
This addon is perfect, but a little problem I have sometimes is on very light colour background where it can be difficult to read Time, Greetings, todos and other widgets. I think that some kind of dark shadow surrounding the white fonts might be perfect for increasing the readability on these kind of background.

**Comment by Excigma** [comment]
Try adding:
```css
.Widgets {
   text-shadow: 7px 7px 5px rgba(0, 0, 0, 0.7);
}
```
To Custom CSS

**Comment by skid9000** [comment]
[Also not a long-term solution]

```css
.Slot.middleCentre {
background-color: rgba(162, 149, 149, 0.28);
border-radius: 6px;
border-bottom: 4px;
}
```
