### ISSUE TITLE
Do not disable the Custom CSS widget when hiding all widgets

### ISSUE THREAD

**Issue by locness3** [joelshepherd/tabliss#242]

**Comment by dimateos** [comment]
Yesss, in my case I use it to dim UI widgets... including the cog and eye that is also displayed when all widgets are hidden:

```css
  .Dashboard.dark {
    color: #ffffff50 !important;
  }
```

So when I hide all widgets the go bright again XD
