### ISSUE TITLE
[Suggestion] Add display style for uploaded images

### ISSUE THREAD

**Issue by HappyDino** [joelshepherd/tabliss#30]
When uploading images, we currently have no choice for the display style resulting in some cropping.
It would be nice if we could choose the style (centered, streched, scaled, zoomed) and the background color (filler for the scaled view).

**Comment by trickypr** [comment]
As of now, you should be able to style it with custom css like:
```css
/* Unsplash uses .image, Custom image uses .Image */
.image, .Image {
  background-size: contain !important;
  background-repeat: no-repeat !important;
  background-color:red !important;
  background-position: top !important;
}
```
