### ISSUE TITLE
GitHub calendar is not resizable 

### ISSUE THREAD

**Issue by iFurane** [joelshepherd/tabliss#579]
It might not be possible for the widget to be resizable due to how it is fetched from the profile.
But if it is possible, then It'd be great!

**Comment by the-wright-jamie** [comment]
The way widgets currently scale appears to be based on font size, so if we scaled via transform as well then it would allow all widgets to transform. I opened a PR to see if it'll be any use, but if it gets accepted it'll break all configs, so I doubt it will, but suggestions would be appreciated

**Comment by the-wright-jamie** [comment]
By the way, I forgot to mention: in the mean time you can use the following Custom CSS to resize it manually.

```css
.GitHub {
    transform-origin: top;
    transform: scale(1); /* CHANGE ME. 1 = DEFAULT SIZE */
}
```

To get Custom CSS, just add the Custom CSS Widget in the Settings menu:  
![image](https://user-images.githubusercontent.com/121819290/223566767-5b50dc68-4e34-4928-8b36-0d3f5d4a609f.png)
