### ISSUE TITLE
Github Contributions map is broken

### ISSUE THREAD

**Issue by happinyz** [joelshepherd/tabliss#620]
Instead of the calendar, it shows text/data of each day.

<img width="1676" alt="image" src="https://github.com/joelshepherd/tabliss/assets/59787978/17d81a2b-d8dc-4244-a167-3132ee02bdb6">

**Comment by alifirhas** [comment]
Glad it's not just me

**Comment by szamanr** [comment]
likely a bug in the library, follow this issue for updates: https://github.com/Bloggify/github-calendar/issues/169

**Comment by Hyperboid** [comment]
Seems to be a CSS issue. Here's a workaround for now:

```css
.sr-only {
    display: none;
}
td.ContributionCalendar-day {
    min-width: 1em;
    min-height: 1em;
}

td.ContributionCalendar-day[data-level='0'] {
    background-color: var(--color-calendar-graph-day-bg);
}

td.ContributionCalendar-day[data-level='1'] {
    background-color: var(--color-calendar-graph-day-L1-bg);
}

td.ContributionCalendar-day[data-level='2'] {
    background-color: var(--color-calendar-graph-day-L2-bg);
}

td.ContributionCalendar-day[data-level='3'] {
    background-color: var(--color-calendar-graph-day-L3-bg);
}

td.ContributionCalendar-day[data-level='4'] {
    background-color: var(--color-calendar-graph-day-L4-bg);
}

td span {
  position: initial !important;
}
```

**Comment by spaceCabbage** [comment]
so im not alone, nice!

**Comment by spaceCabbage** [comment]
> Seems to be a CSS issue. Here's a workaround for now:
> 
> ```css
> .sr-only {
>     display: none;
> }
> td.ContributionCalendar-day {
>     min-width: 1em;
>     min-height: 1em;
> }
> 
> td.ContributionCalendar-day[data-level='0'] {
>     background-color: var(--color-calendar-graph-day-bg);
> }
> 
> td.ContributionCalendar-day[data-level='1'] {
>     background-color: var(--color-calendar-graph-day-L1-bg);
> }
> 
> td.ContributionCalendar-day[data-level='2'] {
>     background-color: var(--color-calendar-graph-day-L2-bg);
> }
> 
> td.ContributionCalendar-day[data-level='3'] {
>     background-color: var(--color-calendar-graph-day-L3-bg);
> }
> 
> td.ContributionCalendar-day[data-level='4'] {
>     background-color: var(--color-calendar-graph-day-L4-bg);
> }
> 
> td span {
>   position: initial !important;
> }
> ```

add a little `border-radius: 2px;`

**Comment by the-wright-jamie** [comment]
> Seems to be a CSS issue. Here's a workaround for now:

Funnily enough, this seems to fix #579 in a weird sort of way 😛

**Comment by yeuk0** [comment]
> Seems to be a CSS issue. Here's a workaround for now:
> 
> ```css
> .sr-only {
>     display: none;
> }
> td.ContributionCalendar-day {
>     min-width: 1em;
>     min-height: 1em;
> }
> 
> td.ContributionCalendar-day[data-level='0'] {
>     background-color: var(--color-calendar-graph-day-bg);
> }
> 
> td.ContributionCalendar-day[data-level='1'] {
>     background-color: var(--color-calendar-graph-day-L1-bg);
> }
> 
> td.ContributionCalendar-day[data-level='2'] {
>     background-color: var(--color-calendar-graph-day-L2-bg);
> }
> 
> td.ContributionCalendar-day[data-level='3'] {
>     background-color: var(--color-calendar-graph-day-L3-bg);
> }
> 
> td.ContributionCalendar-day[data-level='4'] {
>     background-color: var(--color-calendar-graph-day-L4-bg);
> }
> 
> td span {
>   position: initial !important;
> }
> ```

I had change this a bit to be more similar to what we had:

```css
.sr-only {
    display: none;
}

td:first-child {
    display: none;
}

div.js-calendar-graph div:last-child {
    display: none;
}

table.ContributionCalendar-grid thead {
    display: none;
}

td.ContributionCalendar-day[data-level='0'] {
    background-color: var(--color-calendar-graph-day-bg);
}

td.ContributionCalendar-day[data-level='1'] {
    background-color: var(--color-calendar-graph-day-L1-bg);
}

td.ContributionCalendar-day[data-level='2'] {
    background-color: var(--color-calendar-graph-day-L2-bg);
}

td.ContributionCalendar-day[data-level='3'] {
    background-color: var(--color-calendar-graph-day-L3-bg);
}

td.ContributionCalendar-day[data-level='4'] {
    background-color: var(--color-calendar-graph-day-L4-bg);
}
```

**Comment by the-wright-jamie** [comment]
Throwing my hat in the ring - I use my graph top centre, this centres it and adds rounded corners to the boxes:

```css
.GitHub {
    width:100%;
  display: flex;
  justify-content: center;
}
.sr-only {
    display: none;
}

td:first-child {
    display: none;
}

div.js-calendar-graph div:last-child {
    display: none;
}

table.ContributionCalendar-grid thead {
    display: none;
}

td.ContributionCalendar-day {
    border-radius: 3px;
}

td.ContributionCalendar-day[data-level='0'] {
    background-color: var(--color-calendar-graph-day-bg);
}

td.ContributionCalendar-day[data-level='1'] {
    background-color: var(--color-calendar-graph-day-L1-bg);
}

td.ContributionCalendar-day[data-level='2'] {
    background-color: var(--color-calendar-graph-day-L2-bg);
}

td.ContributionCalendar-day[data-level='3'] {
    background-color: var(--color-calendar-graph-day-L3-bg);
}

td.ContributionCalendar-day[data-level='4'] {
    background-color: var(--color-calendar-graph-day-L4-bg);
}
```

Result:
![image](https://github.com/joelshepherd/tabliss/assets/121819290/9871cd7b-3baf-4ebc-bd71-8a27dd079306)

**Comment by benjamin051000** [comment]
How can I apply these workarounds? Not familiar with web dev.

**Comment by the-wright-jamie** [comment]
> How can I apply these workarounds? Not familiar with web dev.

Settings → add widgit → custom css → paste code into textbox

**Comment by krystofyah** [comment]
> 

added min-width since the boxes appeared squished in my browser

```
.GitHub {
    width:100%;
  display: flex;
  justify-content: center;
}
.sr-only {
    display: none;
}

td:first-child {
    display: none;
}

div.js-calendar-graph div:last-child {
    display: none;
}

table.ContributionCalendar-grid thead {
    display: none;
}

td.ContributionCalendar-day {
    border-radius: 3px;
min-width: 10px;

}

td.ContributionCalendar-day[data-level='0'] {
    background-color: var(--color-calendar-graph-day-bg);
}

td.ContributionCalendar-day[data-level='1'] {
    background-color: var(--color-calendar-graph-day-L1-bg);
}

td.ContributionCalendar-day[data-level='2'] {
    background-color: var(--color-calendar-graph-day-L2-bg);
}

td.ContributionCalendar-day[data-level='3'] {
    background-color: var(--color-calendar-graph-day-L3-bg);
}

td.ContributionCalendar-day[data-level='4'] {
    background-color: var(--color-calendar-graph-day-L4-bg);
}
```

**Comment by Mathews-Tom** [comment]
To all those worked the workaround, thanks a lot. Like magic, everything seems to back to normal. YAAY

**Comment by Bruncky** [comment]
It still looks weird on my browsers if I remove the custom CSS; just wanted to mention it before someone nukes their custom CSS without copying it first, as I did 🙃

**Comment by the-wright-jamie** [comment]
> It still looks weird on my browsers 

Yeah, upstream hasn't fixed yet (repo owner is recovering from a knee injury), and I don't know if a version bump on the packages here will be required - if so we might never see it fixed on Tabliss as the owner has been missing on this repo for over a year.

(I've decided to fork and I'm going to make sure it stays maintained, going to try and build a CI pipeline to automatically publish so that the actual work of maintenance is easier)

**Comment by scampanoni** [comment]
> 
I have the same question

**Comment by TriAttack238** [comment]
This extension is also weird for me, but in a new way:
![image](https://github.com/joelshepherd/tabliss/assets/101959987/071fe90d-0cb8-44a3-9fb7-a92014a21b55)

**Comment by davidbudzynski** [comment]
I have the same issue as above

**Comment by LarveyOfficial** [comment]
+1

**Comment by Ethanscharlie** [comment]
+1

**Comment by Ethanscharlie** [comment]
Css still works

**Comment by ouyama-sa** [comment]
It broke again for me, it was working with the CSS up until ~2 days ago, now it doesn't even show up. Completely invisible.

**Comment by bubner** [comment]
Seems like the SSL certificate for api.bloggify.net (and bloggify.net) has expired (upstream provider of gh-calendar map), so this is an upstream fault.

![Image](https://github.com/user-attachments/assets/2d5f8256-ca52-411b-bb83-a39e22e7ea2b)

![Image](https://github.com/user-attachments/assets/98c06fa7-8a47-480c-9ce6-2197cc60523d)

**Comment by bubner** [comment]
> Seems like the SSL certificate for api.bloggify.net (and bloggify.net) has expired (upstream provider of gh-calendar map), so this is an upstream fault.
> 
> ![Image](https://github.com/user-attachments/assets/2d5f8256-ca52-411b-bb83-a39e22e7ea2b)
> 
> ![Image](https://github.com/user-attachments/assets/98c06fa7-8a47-480c-9ce6-2197cc60523d)

I sent them an email, and they fixed the SSL problem. It should show up again now.

**Comment by shr3yas-k** [comment]
The status code has changed from 526 to 200, so it looks like the SSL issue is fixed now.
However, I don't see the calendar(its invisible) - Access-Control-Allow-Origin header seems to be missing.


<img width="1608" height="67" alt="Image" src="https://github.com/user-attachments/assets/df62807e-0d75-4d74-b5e6-183146ddc4f9" />

**Comment by localcatgirl-dev** [comment]
> Seems to be a CSS issue. Here's a workaround for now:
> 
> .sr-only {
>     display: none;
> }
> td.ContributionCalendar-day {
>     min-width: 1em;
>     min-height: 1em;
> }
> 
> td.ContributionCalendar-day[data-level='0'] {
>     background-color: var(--color-calendar-graph-day-bg);
> }
> 
> td.ContributionCalendar-day[data-level='1'] {
>     background-color: var(--color-calendar-graph-day-L1-bg);
> }
> 
> td.ContributionCalendar-day[data-level='2'] {
>     background-color: var(--color-calendar-graph-day-L2-bg);
> }
> 
> td.ContributionCalendar-day[data-level='3'] {
>     background-color: var(--color-calendar-graph-day-L3-bg);
> }
> 
> td.ContributionCalendar-day[data-level='4'] {
>     background-color: var(--color-calendar-graph-day-L4-bg);
> }
> 
> td span {
>   position: initial !important;
> }

I had this issues only on **Firefox**, it works in chromium (helium-browser). This fix it but still it was badly formated so i change it.

```css
.sr-only {
    display: none;
}
td.ContributionCalendar-day {
    min-width: 1em;
    min-height: 1em;
}

td.ContributionCalendar-day[data-level='0'] {
    background-color: var(--color-calendar-graph-day-bg);
}

td.ContributionCalendar-day[data-level='1'] {
    background-color: var(--color-calendar-graph-day-L1-bg);
}

td.ContributionCalendar-day[data-level='2'] {
    background-color: var(--color-calendar-graph-day-L2-bg);
}

td.ContributionCalendar-day[data-level='3'] {
    background-color: var(--color-calendar-graph-day-L3-bg);
}

td.ContributionCalendar-day[data-level='4'] {
    background-color: var(--color-calendar-graph-day-L4-bg);
}

td span {
  position: initial !important;
}

.hide-sm.hide-md.hide-lg.tmp-p-3.color-bg-accent-emphasis.color-fg-on-emphasis.show-on-focus,
.Link--muted {
    display: none !important;
}

.float-right.color-fg-muted.d-flex.flex-items-center
{
    display: none !important;
}
```

## Before Hypefae fix
<details>
<img width="2322" height="1350" alt="Image" src="https://github.com/user-attachments/assets/c986794c-9e7b-410e-be11-a125822f7906" />
</details>

## After Hypefae fix

<details>
<img width="2322" height="1350" alt="Image" src="https://github.com/user-attachments/assets/6d1721eb-2d9d-40f0-8dbe-32476acdb7f5" />
</details>

## After my fix:

<details>
<img width="2322" height="1350" alt="Image" src="https://github.com/user-attachments/assets/36d2b0cd-aa51-4ea0-856a-13bf09557308" />
</details>

## On Chromium (Helium Browser) without any css fix:

<details>
<img width="2322" height="1350" alt="Image" src="https://github.com/user-attachments/assets/b8ab94b7-5f41-4a79-9020-6251cd23f3ae" />
</details>

## And if you want make it simmillar to the chromium version add this to the fix:
```css
td.ContributionCalendar-day[data-level="0"] { 
   background-color: rgb(22, 27, 34)
}

body {
   line-height: 1;
} 
```
<details>
<img width="2322" height="1350" alt="Image" src="https://github.com/user-attachments/assets/9ee2a746-5da1-4be8-b962-dd3394dc9d52" />
</details>
