### ISSUE TITLE
Background image hue/etc filtering option?

### ISSUE THREAD

**Issue by mxmilkiib** [joelshepherd/tabliss#622]
I'm wondering if it could be possible to use CSS to filter the background image in the dimension of hue or monochrome etc.?

**Comment by the-wright-jamie** [comment]
Add Custom CSS widget: 
Settings → Add widget → Custom CSS → Cog → Paste in code

Change hue:

```css
.image {
    filter: hue-rotate(90deg);
}
```

Change monochrome:

```css
.image {
    filter: grayscale(100%);
}
```
