### ISSUE TITLE
[Feature Request] Option to change favicon and hide the "settings" icon.

### ISSUE THREAD

**Issue by kwan-vini** [joelshepherd/tabliss#679]
An option to change the favicon to something else, or have no favicon. In my opinion i just think the default favicon looks kinda ugly.
![image](https://github.com/joelshepherd/tabliss/assets/118130060/46449d96-966b-45c8-aed6-dfd447878f72)
Also add an option to hide the settings icon, or make it only appear when hovering over it.
![image](https://github.com/joelshepherd/tabliss/assets/118130060/00865229-37fb-4f29-a51c-b901676572b4)

**Comment by LouisPhilippeHeon** [comment]
I came here looking for an issue about changing the favicon, I would love to see this getting implemented.

However, you can use this custom css to make the setting icon appear only when hovered.
```css
.Overlay svg {
  display: none;
}
.Overlay:hover svg {
  display: initial !important;
}
```
