### ISSUE TITLE
Put the quote of the day in quotation marks

### ISSUE THREAD

**Issue by HDSQmid** [joelshepherd/tabliss#86]
This should be pretty easy to do. Just add a " to the start and end of each quote.
This would improve readability by a lot

**Comment by eth-p** [comment]
```css

.Quote::before {
    content: '"';
}

.Quote>sub::before {
    position: relative;
    bottom: 5px;
    content: '"';
    font-size: 35px;
}

```
