### ISSUE TITLE
Button to download the background picture

### ISSUE THREAD

**Issue by op3nus3r** [joelshepherd/tabliss#96]
I would find it useful to have a button or a small icon (for example at the bottom left) to download the image in a single click. 
The button could be enabled in the options and not by default to avoid cluttering the interface for those who like to keep it clean and minimal.

**Comment by galacticdessert** [comment]
Add this to your UserChrome.css file:

```css
/*
 * Newtab background will be black
 * reference: https://support.mozilla.org/en-US/questions/1199070
 *            https://www.reddit.com/r/firefox/comments/6s2l0w/removing_the_white_flash_before_a_page_loads/dl9t14q/
 */
@-moz-document url(chrome://browser/content/browser.xul)
{

  #main-window,
  browser[type="content-primary"],
  browser[type="content"],
  tabbrowser#content,
  #content,
  browser[type="content"] > html
  {
     background: #000000 !important;
  }

}
```

references to the source of the fix are in the comment above, and the userChrome.css file can be found by following [this link](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes) .

I would suggest to the maintainer to add this snipped to the main readme, as it seems to be something that a lot of people complain about.

Cheers
